#!/usr/bin/env python3
"""
HTTP service: LinkedIn profile URL in, structured JSON out.

    GET  /api/profile?url=https://www.linkedin.com/in/raj1238
    GET  /health
    POST /admin/reload      (re-read credentials without a redeploy)
    GET  /                  (browser UI)
    GET  /docs              (OpenAPI, generated by FastAPI)

Design notes that matter more than the code:

* One upstream LinkedIn session is shared by every caller, and it is fragile.
  So calls are serialised and spaced (voyager.MIN_INTERVAL_SECONDS), identical
  concurrent requests collapse into one upstream call, and results are cached.
* When the session dies, a breaker trips and every later request is answered
  from memory with 503 + a remedy. Retrying a revoked cookie is how "session
  died" escalates into "account restricted".
"""
import os
import threading
import time

from fastapi import FastAPI, Header, HTTPException, Query, Request
from fastapi.responses import FileResponse, JSONResponse

import normalize
import voyager

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE_TTL = float(os.environ.get("CACHE_TTL_SECONDS", 6 * 3600))
API_KEYS = {k.strip() for k in os.environ.get("API_KEYS", "").split(",") if k.strip()}

app = FastAPI(
    title="LinkedIn Profile API",
    version="0.1.0",
    description="Reverse-engineered LinkedIn profile reader. No browser, no "
                "headless Chrome -- authenticated calls straight to LinkedIn's "
                "internal Voyager REST API.",
)


# --- shared upstream session, with a breaker --------------------------------

class Upstream:
    """Owns the one LinkedIn session and its health."""

    def __init__(self):
        self._lock = threading.Lock()
        self.session = None
        self.error = None          # set when the session is known dead
        self.member = None
        self.started_at = time.time()
        self.reload()

    def reload(self):
        with self._lock:
            self.error = None
            self.member = None
            try:
                self.session = voyager.Session()
            except voyager.CredentialError as e:
                self.session = None
                self.error = {"reason": "not_configured", "detail": str(e)}
                return
            try:
                self.member = self.session.check()
            except voyager.VoyagerError as e:
                self.error = {"reason": e.reason, "detail": str(e), "remedy": e.remedy}

    def trip(self, err):
        """Record a session-level failure so later callers fail fast."""
        with self._lock:
            self.error = {"reason": err.reason, "detail": str(err),
                          "remedy": err.remedy}

    def require(self):
        if self.error:
            raise HTTPException(
                status_code=503,
                detail={"error": self.error["reason"],
                        "message": self.error.get("detail"),
                        "remedy": self.error.get("remedy"),
                        "hint": "POST /admin/reload after updating credentials"},
                headers={"Retry-After": "3600"})
        return self.session


upstream = Upstream()


# --- cache + single flight --------------------------------------------------

_cache = {}                 # vanity -> (expires_at, payload)
_cache_lock = threading.Lock()
_inflight = {}              # vanity -> threading.Lock
_inflight_lock = threading.Lock()


def cache_get(vanity):
    with _cache_lock:
        entry = _cache.get(vanity)
        if not entry:
            return None
        expires_at, payload = entry
        if time.time() >= expires_at:
            _cache.pop(vanity, None)
            return None
        return payload, int(expires_at - time.time())


def cache_put(vanity, payload):
    with _cache_lock:
        _cache[vanity] = (time.time() + CACHE_TTL, payload)


def flight_lock(vanity):
    """One lock per identifier, so N concurrent requests for the same profile
    become one upstream call instead of N."""
    with _inflight_lock:
        return _inflight.setdefault(vanity, threading.Lock())


# --- auth -------------------------------------------------------------------

def check_key(supplied):
    if not API_KEYS:
        return  # unset = open, which is fine locally and flagged by /health
    if supplied not in API_KEYS:
        raise HTTPException(status_code=401,
                            detail={"error": "unauthorized",
                                    "message": "Provide a valid X-API-Key header."})


# --- routes -----------------------------------------------------------------

@app.get("/health/live")
def liveness():
    """Liveness only: is the process up?

    Deliberately separate from /health, which reports 503 when the LinkedIn
    session is dead. A platform health check pointed at /health would kill and
    restart the machine over an expired cookie -- a restart cannot fix a
    credential that is dead in the environment, so that is a crash loop, not a
    recovery. Point orchestrator checks here.
    """
    return {"status": "alive"}


@app.get("/health")
def health():
    healthy = upstream.error is None
    return JSONResponse(
        status_code=200 if healthy else 503,
        content={
            "status": "ok" if healthy else "degraded",
            "session": {
                "authenticated_as": upstream.member,
                "error": upstream.error,
            },
            "cache": {"entries": len(_cache), "ttl_seconds": CACHE_TTL},
            "auth": "api_key" if API_KEYS else "open",
            "uptime_seconds": int(time.time() - upstream.started_at),
        })


@app.post("/admin/reload")
def reload_session(x_api_key: str = Header(default="")):
    """Re-read credentials from the environment and re-probe the session.

    Recovering from a dead cookie should be 'paste and reload', not 'redeploy'.
    """
    check_key(x_api_key)
    upstream.reload()
    return health()


@app.get("/api/profile")
def get_profile(
    url: str = Query(..., description="LinkedIn profile URL, or a bare public "
                                      "identifier such as `raj1238`."),
    refresh: bool = Query(False, description="Bypass the cache for this call."),
    raw: bool = Query(False, description="Return LinkedIn's untouched response "
                                         "instead of the normalized shape."),
    x_api_key: str = Header(default=""),
):
    check_key(x_api_key)

    try:
        vanity = voyager.parse_profile_url(url)
    except voyager.BadProfileUrl as e:
        raise HTTPException(status_code=400,
                            detail={"error": e.reason, "message": str(e),
                                    "remedy": e.remedy})

    if not raw and not refresh:
        hit = cache_get(vanity)
        if hit:
            payload, ttl = hit
            return JSONResponse(content=payload,
                                headers={"X-Cache": "HIT", "X-Cache-TTL": str(ttl)})

    session = upstream.require()

    with flight_lock(vanity):
        # Another request may have filled the cache while we waited for the lock.
        if not raw and not refresh:
            hit = cache_get(vanity)
            if hit:
                payload, ttl = hit
                return JSONResponse(content=payload,
                                    headers={"X-Cache": "HIT", "X-Cache-TTL": str(ttl)})
        try:
            doc, deco = voyager.fetch_profile(session, vanity)
        except voyager.VoyagerError as e:
            if e.fatal_to_session:
                upstream.trip(e)
            raise HTTPException(
                status_code=e.http_status,
                detail={"error": e.reason, "message": str(e), "remedy": e.remedy},
                headers={"Retry-After": "3600"} if e.http_status in (429, 503) else None)

        if raw:
            return JSONResponse(content=doc, headers={"X-Cache": "BYPASS"})

        try:
            payload = normalize.normalize(doc)
        except ValueError as e:
            raise HTTPException(status_code=502,
                                detail={"error": "unparsable_profile",
                                        "message": str(e)})
        payload["_meta"]["decoration_version"] = deco
        payload["_meta"]["fetched_at"] = int(time.time())
        cache_put(vanity, payload)
        return JSONResponse(content=payload, headers={"X-Cache": "MISS"})


@app.get("/", include_in_schema=False)
def index():
    return FileResponse(os.path.join(HERE, "static", "index.html"))


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    """Errors are always a JSON object, never FastAPI's bare string detail."""
    detail = exc.detail
    if not isinstance(detail, dict):
        detail = {"error": "http_error", "message": str(detail)}
    return JSONResponse(status_code=exc.status_code, content=detail,
                        headers=exc.headers)
